[package]
description = "emotion plugin for https://swc.rs"
edition = "2021"
license = "Apache-2.0"
name = "swc_plugin_emotion"
version = "0.1.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "*"
serde_json = "1.0.79"
swc_common = "0.17.21"
swc_emotion = "0.3.0"
swc_plugin = "*"
